"""relacionamento usuario/produto 3

Revision ID: 274b56a412c5
Revises: 8fd3cb331788
Create Date: 2022-07-01 12:42:12.491046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '274b56a412c5'
down_revision = '8fd3cb331788'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
