"""Adiciona coluna tamanho na tabela coluna

Revision ID: 7c8e9c672eba
Revises: 8c47dca3c016
Create Date: 2022-07-01 09:38:46.950568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c8e9c672eba'
down_revision = '8c47dca3c016'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('tamanho', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produto', 'tamanho')
    # ### end Alembic commands ###
